# Generated by Django 4.2 on 2023-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_remove_group_groupchat'),
        ('jwt_auth', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='user_groups', to='groups.group'),
        ),
    ]
