# Generated by Django 4.2 on 2023-04-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
