# Generated by Django 4.2 on 2023-04-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0018_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
