# Generated by Django 4.2 on 2023-05-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0020_user_dislikes_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
    ]
