# Generated by Django 4.2 on 2023-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0022_user_dislikes_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_link',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
