# Generated by Django 4.2 on 2023-05-03 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0004_rating_has_disliked_rating_has_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='has_disliked',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='has_liked',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
