# Generated by Django 4.2 on 2023-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_rating_disliked_by_rating_liked_by_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='has_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
