# Generated by Django 4.2 on 2023-05-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_rating_has_disliked_rating_has_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='liked_by',
        ),
    ]
