# Generated by Django 4.2 on 2023-04-24 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_members'),
        ('groupchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupchat_group', to='groups.group'),
        ),
    ]
