# Generated by Django 4.2 on 2023-04-24 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_group_groupchat'),
        ('groupchat', '0002_alter_groupchat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupchat_messages', to='groups.group'),
        ),
    ]
