# Generated by Django 4.2 on 2023-04-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0005_groupchat_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
