# Generated by Django 4.2 on 2023-04-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_alter_groupchat_group'),
        ('groups', '0006_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupchat',
            field=models.ManyToManyField(blank=True, related_name='groupchat_group', to='groupchat.groupchat'),
        ),
    ]
