# Generated by Django 4.2 on 2023-04-24 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_alter_groupchat_group'),
        ('groups', '0007_group_groupchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupchat',
        ),
        migrations.AddField(
            model_name='group',
            name='groupchat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupchat_group', to='groupchat.groupchat'),
        ),
    ]
