# Generated by Django 4.2 on 2023-04-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_remove_group_groupchat_group_groupchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupchat',
        ),
    ]
