# Generated by Django 4.2 on 2023-04-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_alter_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupchat',
        ),
    ]
