# Generated by Django 4.2 on 2023-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_remove_group_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
