# Generated by Django 4.2 on 2023-05-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('platforms', models.CharField(max_length=100)),
                ('official_site', models.URLField()),
                ('genre', models.ManyToManyField(related_name='albums', to='genres.genre')),
            ],
        ),
    ]
