# Generated by Django 4.2 on 2023-04-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='official_site',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
