# Generated by Django 4.2 on 2023-05-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(max_length=200),
        ),
    ]
